name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_custom_dropdown: ^1.5.0
  cloud_firestore: ^4.17.0
  easy_localization: ^3.0.0

  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_core_web: ^2.11.5
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.10+1


  image_picker: ^1.1.1
  lottie: ^3.1.0
  platform: ^3.1.4
  stylish_bottom_bar: ^1.0.3
  url_launcher: ^6.0.12

lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/logo.png
  - assets/images/marketing1.jpg
  - assets/images/marketing2.jpg
  - assets/images/marketing3.jpg
  - assets/images/icons/fb.png
  - assets/images/KaNa.png
  - assets/images/NaTu.png
  - assets/images/FaSo.png
  - assets/images/SoNa.png
  - assets/images/NaZa.png
  - assets/images/Bus3.jpg
  - assets/images/Bus6.jpg
  - assets/images/Bus1.jpg
  - assets/images/Bus.png
  - assets/images/3map.jpg
  - assets/images/small.jpeg
  - assets/images/back.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

